<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ __('common.spreadsheet_preview') }}</title>
    {!! $spreadsheetStyles !!}
    <style>
        :root {
            color-scheme: light;
            font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
        }

        * {
            box-sizing: border-box;
        }

        html,
        body {
            min-height: 100%;
        }

        body {
            margin: 0;
            color: #0f172a;
            background: #f1f5f9;
        }

        .spreadsheet-preview {
            padding: 1rem;
        }

        .spreadsheet-preview__hint {
            margin: 0 0 0.75rem;
            color: #475569;
            font-size: 0.75rem;
            line-height: 1.25rem;
        }

        .spreadsheet-preview__canvas {
            max-width: 100%;
            overflow: auto;
            border: 1px solid #cbd5e1;
            border-radius: 0.75rem;
            background: #ffffff;
            box-shadow: 0 1px 3px rgb(15 23 42 / 0.08);
        }

        ul.navigation {
            position: sticky;
            top: 0;
            z-index: 2;
            display: flex;
            gap: 0.25rem;
            width: max-content;
            min-width: 100%;
            margin: 0;
            padding: 0.5rem;
            list-style: none;
            border-bottom: 1px solid #cbd5e1;
            background: #f8fafc;
        }

        ul.navigation a {
            display: block;
            padding: 0.375rem 0.75rem;
            border: 1px solid #cbd5e1;
            border-radius: 0.5rem;
            color: #334155;
            background: #ffffff;
            font-size: 0.75rem;
            font-weight: 600;
            text-decoration: none;
        }

        table {
            width: max-content;
            min-width: 100%;
            margin: 0;
            border-collapse: collapse;
            background: #ffffff;
        }

        table + table {
            margin-top: 1rem;
            border-top: 0.5rem solid #e2e8f0;
        }

        td,
        th {
            min-width: 5rem;
            padding: 0.375rem 0.5rem !important;
            border-color: #cbd5e1 !important;
            white-space: nowrap;
        }

        @media (min-width: 640px) {
            .spreadsheet-preview {
                padding: 1.5rem;
            }
        }
    </style>
</head>
<body>
    <main class="spreadsheet-preview" data-spreadsheet-preview>
        <p class="spreadsheet-preview__hint">{{ __('common.spreadsheet_preview_hint') }}</p>
        <div class="spreadsheet-preview__canvas">
            {{-- These fragments are generated by PhpSpreadsheet, which escapes worksheet text values. --}}
            {!! $spreadsheetNavigation !!}
            {!! $spreadsheetContent !!}
        </div>
    </main>
</body>
</html>
