<?php

declare(strict_types=1);

namespace App\Services;

use App\DTOs\Tenant\CashbookEntryDto;
use App\Models\Tenant\Cashbook;
use App\Models\Tenant\CashbookEntry;
use App\Models\Tenant\PaymentRequest;
use App\Models\Tenant\RetirementRequest;
use App\Models\Tenant\User;

class CashbookService
{
    public function recordDisbursement(PaymentRequest $request, User|null $user = null): void
    {
        $branch = $request->branch;
        $currencyId = $branch->currency_id ?? $request->currency_id;

        $cashbook = Cashbook::firstOrCreate(
            ['branch_id' => $request->branch_id],
            ['currency_id' => $currencyId, 'balance' => 0],
        );

        $raw = $request->getAttribute('total_amount');
        $amount = is_numeric($raw) ? (float) $raw : 0.0;

        CashbookEntry::create([
            'cashbook_id' => $cashbook->id,
            'type' => 'credit',
            'amount' => $amount,
            'description' => 'Payment disbursed',
            'entry_date' => today(),
            'sourceable_type' => PaymentRequest::class,
            'sourceable_id' => $request->id,
            'created_by_user_id' => $user?->id,
        ]);

        $cashbook->decrement('balance', $amount);

        activity()
            ->performedOn($cashbook)
            ->causedBy($user)
            ->event('cashbook.credit')
            ->withProperties(['amount' => $amount, 'source' => 'payment_request', 'source_id' => $request->id])
            ->log('Cash debited for disbursement');
    }

    public function recordRetirementSettlement(RetirementRequest $retirement, User|null $user = null): void
    {
        if ($retirement->difference_type === 'nil') {
            return;
        }

        $paymentRequest = $retirement->paymentRequest()->firstOrFail();
        $branch = $paymentRequest->branch;
        $currencyId = $branch->currency_id ?? $paymentRequest->currency_id;

        $cashbook = Cashbook::firstOrCreate(
            ['branch_id' => $paymentRequest->branch_id],
            ['currency_id' => $currencyId, 'balance' => 0],
        );

        $raw = $retirement->getAttribute('difference_amount');
        $amount = is_numeric($raw) ? (float) $raw : 0.0;
        $isCredit = $retirement->difference_type === 'pay_to_staff';
        $type = $isCredit ? 'credit' : 'debit';
        $description = $isCredit
            ? 'Retirement settlement — additional payment to staff'
            : 'Retirement settlement — refund received from staff';
        $event = $isCredit ? 'cashbook.credit' : 'cashbook.debit';

        CashbookEntry::create([
            'cashbook_id' => $cashbook->id,
            'type' => $type,
            'amount' => $amount,
            'description' => $description,
            'entry_date' => today(),
            'sourceable_type' => RetirementRequest::class,
            'sourceable_id' => $retirement->id,
            'created_by_user_id' => $user?->id,
        ]);

        if ($isCredit) {
            $cashbook->decrement('balance', $amount);
        } else {
            $cashbook->increment('balance', $amount);
        }

        activity()
            ->performedOn($cashbook)
            ->causedBy($user)
            ->event($event)
            ->withProperties(['amount' => $amount, 'source' => 'retirement_request', 'source_id' => $retirement->id, 'difference_type' => $retirement->difference_type])
            ->log($isCredit ? 'Cash debited for retirement settlement' : 'Cash credited from retirement refund');
    }

    public function recordManualReceipt(Cashbook $cashbook, CashbookEntryDto $dto, User|null $user = null): void
    {
        $amount = is_numeric($dto->amount) ? (float) $dto->amount : 0.0;

        CashbookEntry::create([
            'cashbook_id' => $cashbook->id,
            'type' => 'debit',
            'amount' => $amount,
            'description' => 'Manual receipt',
            'entry_date' => $dto->entryDate,
            'reference' => $dto->reference,
            'notes' => $dto->notes,
            'sourceable_type' => null,
            'sourceable_id' => null,
            'created_by_user_id' => $user?->id,
        ]);

        $cashbook->increment('balance', $amount);

        activity()
            ->performedOn($cashbook)
            ->causedBy($user)
            ->event('cashbook.receipt')
            ->withProperties(['amount' => $amount])
            ->log('Manual receipt recorded');
    }

    public function deleteManualReceipt(CashbookEntry $entry): void
    {
        if ($entry->isAutoGenerated()) {
            throw new \LogicException('Auto-generated cashbook entries cannot be deleted.');
        }

        $raw = $entry->getAttribute('amount');
        $amount = is_numeric($raw) ? (float) $raw : 0.0;
        $cashbook = $entry->cashbook;

        $cashbook->decrement('balance', $amount);
        $entry->delete();

        activity()
            ->performedOn($cashbook)
            ->event('cashbook.receipt_deleted')
            ->withProperties(['amount' => $amount])
            ->log('Manual receipt deleted');
    }
}
