<?php

declare(strict_types=1);

namespace App\Http\Controllers\Web\Tenant;

use App\Http\Controllers\Controller;
use App\Http\Requests\Tenant\ManualReceiptStoreRequest;
use App\Models\Tenant\Branch;
use App\Models\Tenant\Cashbook;
use App\Models\Tenant\CashbookEntry;
use App\Repositories\BranchRepository;
use App\Repositories\CashbookRepository;
use App\Services\CashbookService;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class CashbookController extends Controller
{
    public function __construct(
        private readonly CashbookRepository $repository,
        private readonly BranchRepository $branchRepository,
        private readonly CashbookService $service,
    ) {}

    public function branches(): View
    {
        $branches = $this->branchRepository->allWithCashbook();

        return view('tenant.cashbook.branches', compact('branches'));
    }

    public function index(Branch $branch): View
    {
        $cashbook = Cashbook::firstOrCreate(
            ['branch_id' => $branch->id],
            ['currency_id' => $branch->currency_id, 'balance' => 0],
        );

        $entries = $this->repository->paginatedEntriesForCashbook($cashbook);

        return view('tenant.cashbook.index', compact('branch', 'cashbook', 'entries'));
    }

    public function create(Branch $branch): View
    {
        $cashbook = Cashbook::firstOrCreate(
            ['branch_id' => $branch->id],
            ['currency_id' => $branch->currency_id, 'balance' => 0],
        );

        return view('tenant.cashbook.create', compact('branch', 'cashbook'));
    }

    public function store(ManualReceiptStoreRequest $request, Branch $branch): RedirectResponse
    {
        $cashbook = Cashbook::firstOrCreate(
            ['branch_id' => $branch->id],
            ['currency_id' => $branch->currency_id, 'balance' => 0],
        );

        /** @var \App\Models\Tenant\User $user */
        $user = $request->user();
        $this->service->recordManualReceipt($cashbook, $request->toDto(), $user);

        return redirect()
            ->route('cashbook.index', $branch)
            ->with('success', 'Receipt recorded successfully.');
    }

    public function destroy(Branch $branch, CashbookEntry $entry): RedirectResponse
    {
        if ($entry->isAutoGenerated()) {
            return redirect()
                ->route('cashbook.index', $branch)
                ->with('error', 'Auto-generated entries cannot be deleted.');
        }

        $this->service->deleteManualReceipt($entry);

        return redirect()
            ->route('cashbook.index', $branch)
            ->with('success', 'Receipt deleted successfully.');
    }
}
