<?php

declare(strict_types=1);

namespace App\Models\Tenant;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model as EloquentModel;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Models\Concerns\HasActivity;

/**
 * @property int $id
 * @property int $cashbook_id
 * @property string $type
 * @property string $amount
 * @property string $description
 * @property \Illuminate\Support\Carbon $entry_date
 * @property string|null $reference
 * @property string|null $notes
 * @property string|null $sourceable_type
 * @property int|null $sourceable_id
 * @property int|null $created_by_user_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property-read Cashbook $cashbook
 * @property-read EloquentModel|\Eloquent $sourceable
 * @property-read User|null $createdBy
 *
 * @method static \Illuminate\Database\Eloquent\Builder<static>|CashbookEntry newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|CashbookEntry newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|CashbookEntry onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|CashbookEntry query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|CashbookEntry withTrashed(bool $withTrashed = true)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|CashbookEntry withoutTrashed()
 *
 * @mixin \Eloquent
 */
class CashbookEntry extends EloquentModel
{
    use HasActivity;
    /** @use HasFactory<\Illuminate\Database\Eloquent\Factories\Factory<static>> */
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'cashbook_id',
        'type',
        'amount',
        'description',
        'entry_date',
        'reference',
        'notes',
        'sourceable_type',
        'sourceable_id',
        'created_by_user_id',
    ];

    /** @return array<string, string> */
    protected function casts(): array
    {
        return [
            'amount' => 'decimal:2',
            'entry_date' => 'date',
        ];
    }

    /** @return BelongsTo<Cashbook, $this> */
    public function cashbook(): BelongsTo
    {
        return $this->belongsTo(Cashbook::class);
    }

    /** @return MorphTo<EloquentModel, $this> */
    public function sourceable(): MorphTo
    {
        return $this->morphTo();
    }

    /** @return BelongsTo<User, $this> */
    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_user_id');
    }

    public function isManual(): bool
    {
        return $this->sourceable_id === null;
    }

    public function isAutoGenerated(): bool
    {
        return $this->sourceable_id !== null;
    }
}
